# Generated by Django 4.2.2 on 2023-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(max_length=270),
        ),
    ]
